DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  employeeId INT AUTO_INCREMENT  PRIMARY KEY,
  empName VARCHAR(250) NOT NULL,
  empEmail VARCHAR(250) NOT NULL,
  location VARCHAR(250) DEFAULT NULL
);